---
deployment:
  tasks:
    - export DEPLOYPATH=/home/theshgye/fit-struction/
    - /bin/cp -R .git $DEPLOYPATH
    - /bin/cp -R bin $DEPLOYPATH
    - /bin/cp -R dbConnection $DEPLOYPATH
    - /bin/cp -R helper $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH